let countryColors = {
  "#f78d94": ["Eastern Africa","Burundi", "Comoros", "Djibouti", "Eritrea", "Ethiopia", "Kenya", "Madagascar", "Malawi", "Mauritius","Mayotte", "Mozambique", "Réunion", "Rwanda", "Seychelles", "Somalia", "South Sudan", "Uganda", "Tanzania", "Zambia", "Zimbabwe"],
  "#f7a57c": ["Middle Africa","Angola", "Cameroon" , "Central African Republic" ,"Chad" , "Congo" , "Democratic Republic of the Congo" , "Equatorial Guinea" ,"Gabon" ,"Sao Tome and Principe"],
  "#fccfc8": ["Nothern Africa","Algeria" , "Egypt" ,"Libya", "Morocco", "Sudan","Tunisia" , "Western Sahara"],
  "#ea8375": ["Southern Africa","Botswana","Eswatini" ,"Lesotho" ,"Namibia" , "South Africa"],
  "#ffc697": ["Western Africa","Benin" , "Burkina Faso" ,"Cabo Verde" , "Côte d'Ivoire" , "Gambia" ,"Ghana" , "Guinea", "Guinea-Bissau" ,"Liberia" ,"Mali" , "Mauritania" ,"Niger" , "Nigeria" , "Saint Helena" , "Senegal", "Sierra Leone" , "Togo"],
  "#49c98f": ["North America","Bermuda",
"Canada", "Greenland",
"Saint Pierre and Miquelon", "United States of America"],
    "#9aed64": ["Central America","Belize" , "Costa Rica",
"El Salvador", "Guatemala",
"Honduras", "Mexico",
"Nicaragua", "Panama"],
      "#eaf76d": ["South America","Argentina",
"Bolivia","Brazil","Chile", "Colombia","Ecuador", "Malvinas","French Guiana", "Guyana","Paraguay", "Peru","Suriname", "Uruguay",
"Venezuela"],
        "#f4ffb6": ["Caribbean","Anguilla","Antigua and Barbuda", "Aruba","Bahamas", "Barbados", 
"British Virgin Islands" , "Cayman Islands","Cuba", "Curaçao",
"Dominica", "Dominican Republic","Grenada", "Guadeloupe","Haiti", "Jamaica",
"Martinique", "Montserrat","Puerto Rico", "Saint Kitts and Nevis",
"Saint Lucia", "Saint Vincent and the Grenadines","Sint Maarten", "Trinidad and Tobago","Turks and Caicos Islands", "United States Virgin Islands","Bonaire, Sint Eustatius and Saba"],
        "#25f4f4": ["Nothern Europe","Channel Islands" , "Denmark" , "Estonia","Faroe Islands" , "Finland" ,"Iceland" , "Ireland",
"Isle of Man", "Latvia" , "Lithuania", "Norway" , "Sweden", "United Kingdom"],
          "#6dd0f7": ["Western Europe","Austria" , "Belgium" , "France" ,"Germany" , "Liechtenstein",
"Luxembourg" , "Monaco","Netherlands" , "Switzerland"],
            "#b6f1ff": ["Southern Europe","Albania" , "Andorra" ,"Bosnia and Herzegovina" ,"Croatia" , "Gibraltar",
"Greece" , "Italy", "Malta" , "Montenegro","North Macedonia" , "Portugal","San Marino", "Serbia","Slovenia" , "Spain", "Holy See","Kosovo"],
              "#34bde8": ["Eastern Europe","Belarus" , "Bulgaria" , "Czechia" ,"Hungary" , "Poland" , "Moldova" , "Romania", "Russia", "Slovakia","Ukraine"],
              "#5f9cff": ["Central Asia","Kazakhstan" , "Kyrgyzstan" , "Tadjikistan" ,"Turkmenistan" , "Uzbekistan"],
              "#4b7cf7": ["Eastern Asia","China" , "Hong Kong", "Macao", "Taiwan", "North Korea" , "Japan" , "Mongolia" , "South Korea"],
                "#aa83ff": ["Southern Asia","Afghanistan", "Bangladesh" , "Bhutan" ,"India" , "Iran" , "Maldives", "Nepal", "Pakistan", "Sri Lanka"],
                  "#7027e2": ["Southeastern Asia","Brunei Darussalam" , "Cambodia" , "Indonesia" , "Laos", "Malaysia", "Myanmar", "Philippines" , "Singapore" , "Thailand" , "Timor-Leste" ,
"Viet Nam"],
                    "#c4b4f9": ["Western Asia","Armenia","Azerbaijan" ,"Bahrain" , "Cyprus", "Georgia",
"Iraq", "Israel", "Jordan", "Kuwait","Lebanon", "Oman","Qatar", "Saudi Arabia" , "Palestine", "Syria" , "Türkiye", "United Arab Emirates" , "Yemen"],
  "#f95ff5": ["Australia & New Zealand","Australia", "New Zealand"],
    "#a71ddb": ["Fiji","New Caledonia", "Papua New Guinea","Solomon Islands", "Vanuatu", "Melanesia"],
      "#bf00c9": ["Guam","Kiribati", "Marshall Islands","Micronesia States", "Nauru", "Northern Mariana Islands", "Palau","Micronesia"],
        "#ffa4fd": ["American Samoa",
"Cook Islands", "French Polynesia",
"Niue", "Samoa", "Tokelau", "Tonga" , "Tuvalu", "Wallis and Futuna Islands","Polynesia"],
};

function getColorForCountry(countryName) {
  for (let col in countryColors) {
    if (countryColors[col].includes(countryName)) {
      return col;
    }
  }
  return "#999"; // fallback color
}

let continents = {
  "Southern Africa": ["Botswana","Eswatini" ,"Lesotho" ,"Namibia" , "South Africa"],
  "Eastern Africa": ["Burundi", "Comoros", "Djibouti", "Eritrea", "Ethiopia", "Kenya", "Madagascar", "Malawi", "Mauritius","Mayotte", "Mozambique", "Réunion", "Rwanda", "Seychelles", "Somalia", "South Sudan", "Uganda", "Tanzania", "Zambia", "Zimbabwe"],
  "Western Africa":  ["Benin" , "Burkina Faso" ,"Cabo Verde" , "Côte d'Ivoire" , "Gambia" ,"Ghana" , "Guinea", "Guinea-Bissau" ,"Liberia" ,"Mali" , "Mauritania" ,"Niger" , "Nigeria" , "Saint Helena" , "Senegal", "Sierra Leone" , "Togo"],
    "Nothern Africa": ["Algeria" , "Egypt" ,"Libya", "Morocco", "Sudan","Tunisia" , "Western Sahara"],
  "Middle Africa": ["Angola", "Cameroon" , "Central African Republic" ,"Chad" , "Congo" , "Democratic Republic of the Congo" , "Equatorial Guinea" ,"Gabon" ,"Sao Tome and Principe"],
    "Melanesia": ["Fiji","New Caledonia", "Papua New Guinea","Solomon Islands", "Vanuatu","Melanesia"],
      "Australia & New Zealand": ["Australia", "New Zealand"],
  "Polynesia" : ["American Samoa",
"Cook Islands", "French Polynesia",
"Niue", "Samoa", "Tokelau", "Tonga" , "Tuvalu", "Wallis and Futuna Islands","Polynesia"],
  "Micronesia" : ["Guam","Kiribati", "Marshall Islands","Micronesia States", "Nauru", "Northern Mariana Islands", "Palau","Micronesia"],
  "Southeastern Asia" :["Brunei Darussalam" , "Cambodia" , "Indonesia" , "Laos", "Malaysia", "Myanmar", "Philippines" , "Singapore" , "Thailand" , "Timor-Leste" ,
"Viet Nam"],
  "Western Asia" : ["Armenia","Azerbaijan" ,"Bahrain" , "Cyprus", "Georgia",
"Iraq", "Israel", "Jordan", "Kuwait","Lebanon", "Oman","Qatar", "Saudi Arabia" , "Palestine", "Syria" , "Türkiye", "United Arab Emirates" , "Yemen"],
  "Central Asia" :["Kazakhstan" , "Kyrgyzstan" , "Tadjikistan" ,"Turkmenistan" , "Uzbekistan"],
  "Southern Asia" :["Afghanistan", "Bangladesh" , "Bhutan" ,"India" , "Iran" , "Maldives", "Nepal", "Pakistan", "Sri Lanka"],
  "Eastern Asia" :["China" , "Hong Kong", "Macao", "Taiwan", "North Korea" , "Japan" , "Mongolia" , "South Korea"],
  "Eastern Europe" : ["Belarus" , "Bulgaria" , "Czechia" ,"Hungary" , "Poland" , "Moldova" , "Romania", "Russia", "Slovakia","Ukraine"],
  "Southern Europe" :["Albania" , "Andorra" ,"Bosnia and Herzegovina" ,"Croatia" , "Gibraltar","Holy See",
"Greece" , "Italy", "Malta" , "Montenegro","North Macedonia" , "Portugal","San Marino", "Serbia","Slovenia" , "Spain"],
  "Western Europe" : ["Austria" , "Belgium" , "France" ,"Germany" , "Liechtenstein",
"Luxembourg" , "Monaco","Netherlands" , "Switzerland"],
  "Nothern Europe":  ["Channel Islands" , "Denmark" , "Estonia","Faroe Islands" , "Finland" ,"Iceland" , "Ireland","Isle of Man", "Latvia" , "Lithuania", "Norway" , "Sweden", "United Kingdom"],
  "South America" : ["Argentina",
"Bolivia","Brazil","Chile", "Colombia","Ecuador", "Malvinas","French Guiana", "Guyana","Paraguay", "Peru","Suriname", "Uruguay",
"Venezuela","Bonaire, Sint Eustatius and Saba"],
  "Caribbean" : ["Anguilla","Antigua and Barbuda", "Aruba","Bahamas", "Barbados", 
"British Virgin Islands" , "Cayman Islands","Cuba", "Curaçao",
"Dominica", "Dominican Republic","Grenada", "Guadeloupe","Haiti", "Jamaica",
"Martinique", "Montserrat","Puerto Rico", "Saint Kitts and Nevis",
"Saint Lucia", "Saint Vincent and the Grenadines","Sint Maarten", "Trinidad and Tobago","Turks and Caicos Islands", "United States Virgin Islands"],
  "Central America": ["Belize" , "Costa Rica",
"El Salvador", "Guatemala",
"Honduras", "Mexico",
"Nicaragua", "Panama"],
  "North America" : ["Bermuda",
"Canada", "Greenland",
"Saint Pierre and Miquelon", "United States of America"]
};